# Generated by Django 2.2.24 on 2021-12-30 16:44

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("authnapp", "0007_auto_20211225_2115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 1, 1, 16, 44, 17, 220060, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        ),
    ]
