# Generated by Django 2.2.24 on 2021-12-30 16:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20211230_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 1, 16, 46, 26, 803674, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
